In [1]:
from utilities.load_data import *
from Stereo.Aggregation.aggregation import *
from Stereo.Costs.costs import *
from Stereo.Disparity_computing.disparty_computing import *
from Stereo.Main_Pipeline import *

Costs: StereoCost.SAD SSD STAD NCC
Aggregation: fixed_window(),
DisparityComputation: winner takes all

In [2]:
image_name='Road'


In [4]:
cost_function=StereoCost.SAD
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=64).compute_disparity_map()

375 1242


  0%|          | 0/371 [00:00<?, ?it/s]

100%|██████████| 371/371 [06:28<00:00,  1.05s/it]


Single image mode


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 29,  0,  0],
       ...,
       [ 0,  0,  0, ..., 45,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [5]:
cost_function=StereoCost.SAD
aggregation_function=fixed_window(11)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=64).compute_disparity_map()

375 1242


100%|██████████| 365/365 [06:20<00:00,  1.04s/it]


Single image mode


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [6]:
cost_function=StereoCost.SAD
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=96).compute_disparity_map()

375 1242


100%|██████████| 371/371 [09:46<00:00,  1.58s/it]


Single image mode


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 29,  0,  0],
       ...,
       [ 0,  0,  0, ..., 45,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [7]:
cost_function=StereoCost.SSD
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=64).compute_disparity_map()

375 1242


100%|██████████| 371/371 [06:32<00:00,  1.06s/it]


Single image mode


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 33,  0,  0],
       ...,
       [ 0,  0,  0, ..., 59,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [8]:
cost_function=StereoCost.STAD
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=64).compute_disparity_map()

375 1242


100%|██████████| 371/371 [5:46:34<00:00, 56.05s/it]      


Single image mode


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 33,  0,  0],
       ...,
       [ 0,  0,  0, ..., 45,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [9]:
cost_function=StereoCost.NCC
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=64).compute_disparity_map()

375 1242


  0%|          | 0/371 [00:00<?, ?it/s]/home/ymachta/StereoMatching/Stereo/Costs/costs.py:29: RuntimeWarning: invalid value encountered in scalar divide
  NCC = np.sum((intensites_left - mean_left)*(intensities_right - mean_right))/(std_left*std_right)
 13%|█▎        | 49/371 [08:02<52:49,  9.84s/it] 


KeyboardInterrupt: 

In [10]:
cost_function=StereoCost.SSD
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=96).compute_disparity_map()

375 1242


100%|██████████| 371/371 [09:25<00:00,  1.53s/it]


Single image mode


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 33,  0,  0],
       ...,
       [ 0,  0,  0, ..., 70,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [11]:
cost_function=StereoCost.STAD
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation()
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=96).compute_disparity_map()

375 1242


100%|██████████| 371/371 [27:18<00:00,  4.42s/it]   


Single image mode


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 33,  0,  0],
       ...,
       [ 0,  0,  0, ..., 45,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [ ]:
cost_function=StereoCost.SSD
aggregation_function=fixed_window(5)
disparity_computation=DisparityComputation(strategy='dynamic-programming')
disparity_refinement=None
StereoPipeline(image_name,
                cost_function, 
                aggregation_function,
                disparity_computation,
                disparity_refinement,
                max_disparity=96).compute_disparity_map()